name: Bump version and auto-release (docker)
#this is a pipeline. all pipelines have jobs in them. 
#steps are the commands we give the file 
on:
  push: 

jobs:
  push-docker:
    name: Push docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: openclimatefix
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: internal_ui:${{ github.sha }}